<a href="https://colab.research.google.com/github/rekuantsun/Hoc-May/blob/main/Bai4_Huanluyenmohinhvaloi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import os
import numpy as np
from sklearn.model_selection import train_test_split
folder = "/content"
filename = "ex1data1.txt"
D = np.loadtxt(os.path.join(folder, filename), delimiter=',')
X, y = D[:,:-1], D[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=15)

In [12]:
X_train

array([[10.236 ],
       [ 6.4296],
       [ 5.1793],
       [ 7.2182],
       [ 6.5159],
       [ 9.1802],
       [ 5.7737],
       [ 5.3077],
       [ 5.8918],
       [ 6.3557],
       [ 5.0702],
       [13.394 ],
       [ 7.2259],
       [ 9.3102],
       [ 7.5386],
       [11.7   ],
       [ 5.5649],
       [ 7.4239],
       [ 5.0365],
       [ 9.7687],
       [11.708 ],
       [ 8.5186],
       [ 8.5781],
       [ 5.8598],
       [ 7.9334],
       [ 5.8707],
       [ 5.7077],
       [ 5.4369],
       [ 5.0269],
       [ 5.4901],
       [ 5.4069],
       [ 8.2951],
       [ 6.8825],
       [ 7.4764],
       [ 7.6031],
       [ 7.5402],
       [ 8.2111],
       [12.828 ],
       [ 5.5204],
       [ 5.5277],
       [ 5.5416],
       [ 6.2742],
       [ 5.7292],
       [22.203 ],
       [ 8.8254],
       [ 7.8247],
       [ 7.0708],
       [ 5.6063],
       [ 6.3534],
       [ 5.4994],
       [ 5.3794],
       [ 5.7107],
       [21.279 ],
       [ 9.2482],
       [ 6.3261],
       [ 6

In [13]:
X_test

array([[10.274 ],
       [ 5.1077],
       [ 5.6397],
       [ 7.6366],
       [14.164 ],
       [20.341 ],
       [ 6.3589],
       [ 5.1884],
       [ 5.6407],
       [ 5.0594],
       [ 7.0931],
       [20.27  ],
       [ 8.0959],
       [ 6.4862],
       [ 9.4536],
       [ 6.3328],
       [ 5.0546],
       [18.945 ],
       [ 8.2934],
       [ 6.002 ],
       [ 7.0032],
       [ 6.1891],
       [18.959 ],
       [14.908 ],
       [10.136 ],
       [ 5.3054],
       [12.836 ],
       [ 8.4084],
       [ 6.3654],
       [ 5.2524]])

In [14]:
y_train

array([ 7.7754 ,  3.6518 , -0.74279,  4.8852 ,  5.3436 ,  6.7981 ,
        2.4406 ,  1.8396 ,  1.8495 ,  0.67861,  5.1337 ,  9.0551 ,
        3.3411 ,  3.9624 ,  3.8845 ,  8.0043 ,  3.0825 ,  4.2885 ,
        5.7014 ,  7.5435 ,  5.3854 , 13.662  , 12.     ,  6.8233 ,
        4.5623 ,  7.2029 ,  1.8451 ,  0.61705, -2.6807 ,  4.263  ,
        0.55657,  5.7442 ,  3.9115 ,  4.3483 ,  4.9981 ,  6.7504 ,
        6.5426 , 13.501  ,  0.152  ,  9.1302 ,  1.0179 ,  2.4756 ,
        0.47953, 24.147  ,  5.1694 ,  6.7318 ,  5.3893 ,  3.3928 ,
        5.4974 ,  1.0173 ,  3.5129 ,  3.2522 , 17.929  , 12.134  ,
        5.1875 ,  5.9966 ,  0.56077,  1.844  ,  4.2415 ,  0.29678,
        4.0259 ,  7.0467 , 14.692  , 17.592  , 11.886  ,  3.1551 ,
        1.2784 ])

In [15]:
y_test

array([ 6.7526 ,  2.0576 ,  4.6042 ,  4.2959 , 15.505  , 20.992  ,
       -1.4211 ,  0.20421,  0.71618,  2.8214 ,  1.0463 , 21.767  ,
        4.1164 ,  6.5987 ,  5.4141 ,  1.4233 ,  3.8166 , 22.638  ,
        0.14454,  0.92695, 11.854  ,  3.1386 , 17.054  , 12.054  ,
        6.6799 ,  1.9869 , 10.117  ,  7.2258 ,  5.3048 , -1.22   ])

# 1) Hãy liệt kê tất cả tham số của hàm train_test_split() và ý nghĩa của chúng.

Thông số:

**arrays: chuỗi các chỉ mục có cùng độ dài/hình dạng[0]**

Đầu vào được phép là danh sách, mảng gọn gàng, ma trận scipy-thưa thớt hoặc khung dữ liệu gấu trúc.

**test_size: float hoặc int, default=None**

Nếu là float, giá trị này phải nằm trong khoảng từ 0,0 đến 1,0 và biểu thị tỷ lệ của tập dữ liệu được đưa vào phân tách thử nghiệm. Nếu int, đại diện cho số lượng mẫu thử nghiệm tuyệt đối. Nếu Không, giá trị được đặt thành phần bù của kích thước đoàn tàu. Nếu train_size cũng là Không, nó sẽ được đặt thành 0,25.

**train_size: float hoặc int, default=None**

Nếu thả nổi, phải nằm trong khoảng từ 0,0 đến 1,0 và biểu thị tỷ lệ của tập dữ liệu sẽ bao gồm trong quá trình phân tách tàu. Nếu int, đại diện cho số lượng mẫu tàu tuyệt đối. Nếu Không, giá trị sẽ tự động được đặt thành phần bù của kích thước thử nghiệm.

**Random_state: int, RandomState dụ hoặc Không, default=None**

Kiểm soát việc xáo trộn được áp dụng cho dữ liệu trước khi áp dụng phân tách. Truyền một int cho đầu ra có thể lặp lại qua nhiều lệnh gọi hàm. Xem Thuật ngữ.

**shuffle: bool, mặc định=True**

Có xáo trộn dữ liệu trước khi tách hay không. Nếu shuffle=False thì phân tầng phải là Không có.

**stratify: dạng mảng, default=None**

Nếu không phải là Không, dữ liệu được phân chia theo kiểu phân tầng, sử dụng dữ liệu này làm nhãn lớp. Đọc thêm trong Hướng dẫn sử dụng.

# 2) Tại sao khi thực hiện chia train – test, nên lựa chọn tham số shuffle = True? (lưu ý đây là giá trị mặc định)

Tham số **shuffle** là cần thiết để ngăn việc gán không ngẫu nhiên cho tập huấn luyện và kiểm tra. Với shuffle = Truebạn tách dữ liệu một cách ngẫu nhiên. Ví dụ: giả sử bạn có dữ liệu phân loại nhị phân cân bằng và dữ liệu được sắp xếp theo nhãn. Nếu bạn chia nó theo tỷ lệ 80:20 để huấn luyện và kiểm tra, thì dữ liệu kiểm tra của bạn sẽ chỉ chứa các nhãn từ một lớp. Xáo trộn ngẫu nhiên ngăn chặn điều này.