<a href="https://colab.research.google.com/github/rekuantsun/Hoc-May/blob/main/baitaptailop2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [12]:
#1
X = np.array([[1,2,3,4,5],[6,7,8,9,2],[4,5,7,2,1]])
print (X)
X = X.reshape(5,3)
print(X)

[[1 2 3 4 5]
 [6 7 8 9 2]
 [4 5 7 2 1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 4 5]
 [7 2 1]]


In [9]:
#2
w = np.array([2,4,2]).reshape(-1,1)
print (w)

[[2]
 [4]
 [2]]


In [14]:
#3
hw = X.dot(w)
print (hw)

print(hw.ndim)
print(hw.shape)

[[16]
 [40]
 [64]
 [30]
 [24]]
2
(5, 1)


In [16]:
#4
y= np.reshape([1,2, 3, 2, 1], (5, 1))
print(y)

[[1]
 [2]
 [3]
 [2]
 [1]]


In [18]:
#5
hieu = hw - y
print('dimension: ', hieu.ndim)
print(hieu.shape)
print(hieu)

dimension:  2
(5, 1)
[[15]
 [38]
 [61]
 [28]
 [23]]


In [19]:
#6
h2 = np.dot(X.T, hieu)
print('dimension: ', h2.ndim)
print(h2.shape)
print(h2)

dimension:  2
(3, 1)
[[811]
 [866]
 [985]]
