<a href="https://colab.research.google.com/github/rekuantsun/Hoc-May/blob/main/Baitaptailop1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

MÃ LỆNH PYTHON

Thư viện

In [1]:
import numpy as np

In [2]:
#1
v = np.array([1,2,3,4,5])

In [9]:
#2
w = np.array([1,2,3,4,5]).reshape(-1,1)

In [10]:
#3
v.ndim
w.ndim
print(v.shape)
print(w.shape)
print(v)
print(w)

(5,)
(5, 1)
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [11]:
#4
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
X = np.column_stack((x,y))
print(X)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [12]:
#5 
X = np.array([1,2,3,4,5,6,7,8,9,2,4,5,7,2,1]).reshape(3,5)
print(X)
print(X.ndim, X.shape)

[[1 2 3 4 5]
 [6 7 8 9 2]
 [4 5 7 2 1]]
2 (3, 5)


In [13]:
#6
Xv = np.dot(X,v)
print(Xv)
print(Xv.ndim, Xv.shape)

[55 90 48]
1 (3,)


In [14]:
#7
Xw = np.dot(X,w)
print(Xw)
print(Xw.ndim, Xw.shape)

[[55]
 [90]
 [48]]
2 (3, 1)


In [15]:
#8
XT = X.T
print(XT)

[[1 6 4]
 [2 7 5]
 [3 8 7]
 [4 9 2]
 [5 2 1]]
