<a href="https://colab.research.google.com/github/rekuantsun/Hoc-May/blob/main/BTVN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Thư viện
import numpy as np

In [3]:
# Đại lượng vô hướng - tensor hạng 0
x = 5
y = -12
z = 3.1417

In [4]:
# Đại lượng có hướng - vector - tensor hạng 1
x = np.array([2, -1, 3, 6])

# Kiểm tra số chiều
print(x.ndim)

# Kiểm tra kích thước
print(x.shape)

1
(4,)


In [5]:
# Ma trận - tensor hạng 2
X = np.array([1, 2, 3, 4, 5, 6]).reshape((2,3))
print(X)

[[1 2 3]
 [4 5 6]]


In [7]:
# Tensor hạng 3
X = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((3,2,2))
print(X)

# Kiểm tra số chiều và kích thước 
print(X.ndim)
print(X.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)


In [9]:
from matplotlib import pyplot as plt
img = plt.imread('/content/drive/MyDrive/Classroom/Học máy 1 Phần cơ sở/pexels-宗轩-李-10099637.jpg')
print(img.ndim)
print(img.shape)

3
(5184, 3456, 3)


In [ ]:
# Câu hỏi mở rộng: Theo bạn biểu diễn (hay mô tả) Toán học của đoạn phim (video) là gì? 
