<a href="https://colab.research.google.com/github/rekuantsun/Hoc-May/blob/main/BTVN1_motatoanhoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Thư viện
import numpy as np

In [3]:
# Đại lượng vô hướng - tensor hạng 0
x = 5
y = -12
z = 3.1417

In [4]:
# Đại lượng có hướng - vector - tensor hạng 1
x = np.array([2, -1, 3, 6])

# Kiểm tra số chiều
print(x.ndim)

# Kiểm tra kích thước
print(x.shape)

1
(4,)


In [5]:
# Ma trận - tensor hạng 2
X = np.array([1, 2, 3, 4, 5, 6]).reshape((2,3))
print(X)

[[1 2 3]
 [4 5 6]]


In [6]:
# Tensor hạng 3
X = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape((3,2,2))
print(X)

# Kiểm tra số chiều và kích thước 
print(X.ndim)
print(X.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3
(3, 2, 2)


In [7]:
from matplotlib import pyplot as plt
img = plt.imread('/content/drive/MyDrive/Classroom/Học máy 1 Phần cơ sở/pexels-宗轩-李-10099637.jpg')
print(img.ndim)
print(img.shape)

3
(5184, 3456, 3)


In [8]:
# Câu hỏi mở rộng: Theo bạn biểu diễn (hay mô tả) Toán học của đoạn phim (video) là gì? 
from IPython.display import HTML
from base64 import b64encode
mp4 = open('/story.mp4','rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()
HTML("""

      %s" type="video/mp4">

""" % data_url)

In [10]:
import cv2
frames = []

path = "/story.mp4"
cap = cv2.VideoCapture(path)
ret = True
while ret:
    ret, img = cap.read() 
    if ret:
        frames.append(img)
video = np.stack(frames, axis=0)
print(video)

[[[[ 75  88  86]
   [ 75  88  86]
   [ 73  86  84]
   ...
   [154 161 168]
   [155 162 169]
   [155 162 169]]

  [[ 75  88  86]
   [ 75  88  86]
   [ 73  86  84]
   ...
   [154 161 168]
   [155 162 169]
   [155 162 169]]

  [[ 75  88  86]
   [ 75  88  86]
   [ 73  86  84]
   ...
   [153 160 167]
   [153 160 167]
   [153 160 167]]

  ...

  [[163 153 162]
   [163 153 162]
   [163 153 162]
   ...
   [144 167 151]
   [144 167 151]
   [144 167 151]]

  [[144 149 175]
   [144 149 175]
   [145 150 176]
   ...
   [144 160 165]
   [144 160 165]
   [144 160 165]]

  [[141 146 172]
   [141 146 172]
   [141 146 172]
   ...
   [143 159 164]
   [143 159 164]
   [143 159 164]]]


 [[[ 89 102 100]
   [ 88 101  99]
   [ 85  98  96]
   ...
   [153 163 169]
   [153 160 167]
   [151 158 165]]

  [[ 90 103 101]
   [ 89 102 100]
   [ 84  97  95]
   ...
   [152 162 168]
   [153 160 167]
   [152 159 166]]

  [[ 93 106 104]
   [ 90 103 101]
   [ 84  97  95]
   ...
   [153 160 167]
   [152 159 166]
   [151 158